name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build project
        run: msbuild -property:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Upload to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: IntelVoltageControl-${{ matrix.configuration }}
          path: x64
